// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Runtime.InteropServices;
 
// General Information about product.
[assembly: AssemblyProduct("OpenHTM")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//

[assembly: AssemblyVersion("0.0.879.53")]
[assembly: AssemblyFileVersion("0.0.879.53")]
